export const SET_PROJECTS_DATA = "SET_PROJECTS_DATA"

export const SET_USER = "SET_USER"
export const SET_USER_DATA = "SET_USER_DATA"
export const SET_SETUP_COMPLETED = "SET_SETUP_COMPLETED"

export const LOGOUT = "LOGOUT"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_ERROR = 'LOGIN_USER'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_ERROR = 'REGISTER_USER'

export const UPLOAD_TEXT = 'UPLOAD_TEXT'
export const UPLOAD_TEXT_ERROR = 'UPLOAD_TEXT_ERROR'
